FROM jamesmcclain/accumulo:8u111
MAINTAINER James McClain <james.mcclain@gmail.com>

ENV GEOWAVE_HOME /usr/local/geowave

ADD geowave-tools.sh ${GEOWAVE_HOME}/tools/
ADD geowave-tools.jar ${GEOWAVE_HOME}/tools/
ADD plugins/ ${GEOWAVE_HOME}/tools/plugins/
ADD geowave-analytic-mapreduce.jar ${GEOWAVE_HOME}/tools/
ADD geowave-accumulo.jar /opt/accumulo-1.7.2/lib/ext/
ADD leader.sh /scripts/

CMD ["/scripts/leader.sh"]
